### PR TITLE
fix(go): major version is incorrectly stripped from package names

### LINKED ISSUE #215: Go release incorrectly creating tags for packages with version in the package name
Tags are not being created correctly for the awscdkapigatewayv2 alpha modules. The v2 is being stripped from the name so instead of awscdkapigatewayv2alpha/v2.0.0-rc.24 we are getting awscdkapigatewayalpha/v2/v2.0.0-rc.24

### PR DESCRIPTION
**Pull request by corymhall**
if the package name includes a major version string such as 'v2' we
should not remove it when creating tag names. For example when
creating the tag for version v2.0.0-alpha.4 and package
awscdkapigatewayv2alpha the tag name should be
'awscdkapigatewayv2alpha/v2.0.0-alpha.4'

fixes #215

### CODE REVIEW

File: src/targets/go.ts [hunk 1]
```diff
@@ -264,8 +264,16 @@ export class GoReleaser {
...
-      .join('/') // e.g 'constructs/v3'
-      .replace(`v${majorVersion}`, ''); // e.g 'constructs/'
+      .join('/'); // e.g 'constructs/v3'
+
+    // we could have something like
+    // constructs/v3
+    // or something like
+    // constructsv3/v3
+    // we only want to strip the last 'v3'
+    if (repoPath.endsWith(`v${majorVersion}`)) {
```
Comment (iliapolo) [inline src/targets/go.ts:274]: Feels more robust:

```suggestion
    if (repoPath.endsWith(`/v${majorVersion}`)) {
```

**Review by iliapolo — CHANGES_REQUESTED** [review]

**Review by iliapolo — APPROVED** [review]
